-- CRIAÇÃO DAS TABELAS PARA O SISTEMA DE SUPORTE TÉCNICO

-- 1. Tabela de Perfis de Usuário
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabela de Categorias
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Tabela de Status
CREATE TABLE statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color_class TEXT DEFAULT 'bg-surface-container-high text-on-surface-variant',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela de Chamados (Tickets)
CREATE TABLE tickets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  subject TEXT NOT NULL,
  description TEXT,
  priority TEXT DEFAULT 'Média' CHECK (priority IN ('Baixa', 'Média', 'Alta', 'Crítica')),
  category_id BIGINT REFERENCES categories(id),
  status_id BIGINT REFERENCES statuses(id),
  user_id UUID REFERENCES profiles(id),
  assigned_to UUID REFERENCES profiles(id),
  actions_taken TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Tabela de Configurações do Sistema
CREATE TABLE system_config (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT DEFAULT 'TechSupport',
  subtitle TEXT DEFAULT 'Enterprise Console',
  logo_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- POPULAR DADOS DE EXEMPLO

INSERT INTO categories (name) VALUES 
('Informática/TI'), 
('Elétrica'), 
('Predial/Civil'), 
('Segurança Eletrônica'), 
('Telecomunicações');

INSERT INTO statuses (name, color_class) VALUES 
('Pendente', 'bg-surface-container-high border-outline-variant text-on-surface-variant'),
('Em Progresso', 'bg-primary/10 border-primary/20 text-primary'),
('Validando', 'bg-tertiary/10 border-tertiary/20 text-tertiary'),
('Concluído', 'bg-outline/10 border-outline/20 text-outline');

INSERT INTO system_config (title, subtitle, logo_url) VALUES 
('TechSupport', 'Enterprise Console', 'https://lh3.googleusercontent.com/aida-public/AB6AXuAacE4yTsNlGsHfRtRDtZb54RI9ANjGG3QtH6A637LXkHGEu8kx4w_fg0DacMthMQTHFHMGirSX3JycjkH853x0_rf1-9ZF3gn_xlLNEj4p9XrNpuAHvAVcV0UexvVHO-BFmc1DsYaEvI4nS2rltb6pZBrpMK-cYOfHwO3IwwYqb7_7uX1xuom5WgihWSpsbbVIOgwgOzP_T45snIex9ZVrjiYDQLSYRU8F7zJbHgvg0ocI_1HK-dNXFHQorkhnKEN3JUnOYGI3AD-v');

-- HABILITAR RLS (Row Level Security) - Exemplo básico permitindo leitura para todos
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública de categorias" ON categories FOR SELECT USING (true);

ALTER TABLE statuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública de status" ON statuses FOR SELECT USING (true);

ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuários veem seus próprios tickets" ON tickets FOR SELECT USING (auth.uid() = user_id OR (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');
